# Generated by Django 3.2 on 2021-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', 'trigrams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(help_text='State of the city', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
