# Generated by Django 3.2 on 2021-04-16 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Book title', max_length=100)),
                ('author', models.CharField(help_text="Author name or comma separated list of authors' names", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the offer')),
                ('city', models.CharField(help_text='General area of an exchange place', max_length=50)),
                ('state', models.CharField(help_text='State of city', max_length=50)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('LT', 'Lent'), ('RT', 'Returned')], default='AC', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lender_phone', models.CharField(help_text="Lender's contact information", max_length=13)),
                ('lender', models.ForeignKey(help_text='Who offered to lend a book', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
    ]
