name: Android Build

on:
  push:
    branches:
      - develop
      - release
      - master
  pull_request:
    branches:
      - develop
      - release
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x app/gradlew
      - name: Build with Gradle
        run: ./app/gradlew build
      - name: Run android tests with coverage
        working-directory: ./app/src/app/androidTest/java/com/example/bookbook
        run: coverage run *.java coverage report --fail-under=50
      - name: Run tests with coverage
        working-directory: ./app/src/app/test/java/com/example/bookbook
        run: coverage run *.java coverage report --fail-under=50