# This is a basic workflow to help you get started with Actions

name: backend-CI

# Controls when the action will run. 
on:
  push:
    branches:
      - develop
      - release
      - master
  pull_request:
    branches:
      - develop
      - release
      - master

jobs:
  build-and-tests-dev:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
    env:
      SECRET_KEY: github-actions-secret-key
      DB_NAME: github-actions
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DEBUG: 1
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.8'
      - name: install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: install dependencies
        working-directory: ./backend
        run: pipenv install
      - name: Run migrations
        working-directory: ./backend
        run: python manage.py migrate
      - name: run tests
        working-directory: ./backend
        run: python manage.py test

